### ISSUE TITLE
Stdout doesn't include timestamps 

### ISSUE THREAD

**Issue by radumas** [SAUSy-Lab/nb-gtfs#30]
Running `store.py` with `nohup` continuously and the current contents of `nohup.out` the log file for stdout is
```
1068 in fleet, 4 ending trips
1066 in fleet, 6 ending trips
1066 in fleet, 5 ending trips
1065 in fleet, 4 ending trips
1065 in fleet, 11 ending trips
```
And so on, which isn't particularly useful given the lack of timestamps. Thoughts on adding timestamps or other info to this output?

**Comment by Nate-Wessel** [comment]
Good idea. I never really intended it to go into a log file - I always just watched the things scroll by to assure myself that everything is working. But it's easy enough to add a timestamp.

**Comment by Nate-Wessel** [comment]
Timestamps added :-)
